namespace MTTFC
{
    public class ConvertService
    {
        /// <summary>
        /// A delegate to support logging
        /// </summary>
        /// <param name="s">The string to log.</param>
        /// <param name="args">The arguments.</param>
        public delegate void LogAction(string s, params object[] args);

        private LogAction Log { get; }

        private readonly ConvertServiceParameters OriginalParameters;

        public ConvertService(LogAction log, ConvertServiceParameters paramters)
        {
            OriginalParameters = paramters;
            Log = log;
        }

        public bool Execute()
        {
            Log("Starting MTT ConvertService");
            var localWorkingDir = ConvertServiceHelper.GetWorkingDirectory(Log, OriginalParameters.WorkingDirectory);
            var localConvertDir = ConvertServiceHelper.GetConvertDirectory(Log, OriginalParameters.ConvertDirectory);

            var models = ConvertServiceModelLoader.GetModels(localWorkingDir, localWorkingDir);

            ConvertServiceModelFiller.BreakDown(models, localWorkingDir);
            ConvertServiceConverter.Convert(Log, models, localConvertDir, OriginalParameters.PathStyle, OriginalParameters.EnumValues, OriginalParameters.IsAutoGeneratedTag);

            Log("Finished MTT ConvertService");
            return true;
        }
    }
}
